name: newfeedCICD
on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t rahultantisoftware555/newfeed .
      - name: Publish image to docker hub
        run: docker push rahultantisoftware555/newfeed
  deploy:
    needs: build
    runs-on: [aws-ec2-newfeed]
    steps:
      - name: Pull Image from docker hub
        run: docker pull in rahultantisoftware555/newfeed
      - name: Delete old container
        run: docker rm -f newfeed-container
      - name: Run docker container
        run: docker run -d -p 8086:8086 --name newfeed-container rahultantisoftware555/newfeed




